platform: ubuntu # | osx

build:
- make clean
- make

test:
- ./hello

analyzers:
 - golint: false
   path: ./transfersh-server/
   min_confidence: 0.8
 - govet: false 
   path: ./transfersh-server/
 - jslint: false
   params: 
   - evil
 - eshint: false
   params: test2
 - dartanalyzer: true
 - jsxhint: false
 - jshint: false
 - eslint: false
 - coffeelint: true
 - scalastyle: true
 - rubocop: false
   targets: ["."]
 - csslint: false
   errors:
   warnings:
   ignore:
   exclude-list:
 - phpcs: false
 - shellcheck: false
   interpreter: zsh
 - elvis: true
 - polysquare-cmake: false
   allowed: ["CMakeLists.txt"]
 - flake8: false
 - pmd: false
 - markdownlint: true
 - checkstyle: false
   style: google # | sun
